# Dockerfile

FROM node:18-alpine

WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install

COPY frontend ./
RUN npm run build

EXPOSE 8080
ENV PORT=8080

ENTRYPOINT ["node", "build"]